spring.application.name=integrationHub

# Server
server.port=8080

# Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ai
spring.datasource.username=postgres
spring.datasource.password=blah123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info